<?php

declare(strict_types=1);

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Clear selection' => 'Limpar seleção',
    'Close picker' => 'Fechar seletor',
    'Date' => 'Data',
    'Decrement hour' => 'Diminuir hora',
    'Decrement minute' => 'Diminuir minuto',
    'Decrement second' => 'Diminuir segundo',
    'Go to today' => 'Ir para hoje',
    'Increment hour' => 'Aumentar hora',
    'Increment minute' => 'Aumentar minuto',
    'Increment second' => 'Aumentar segundo',
    'Next century' => 'Próximo século',
    'Next decade' => 'Próxima década',
    'Next month' => 'Próximo mês',
    'Next year' => 'Próximo ano',
    'Pick hour' => 'Selecionar hora',
    'Pick minute' => 'Selecionar minuto',
    'Pick second' => 'Selecionar segundo',
    'Previous century' => 'Século anterior',
    'Previous decade' => 'Década anterior',
    'Previous month' => 'Mês anterior',
    'Previous year' => 'Ano anterior',
    'Select date' => 'Selecionar data',
    'Select decade' => 'Selecionar década',
    'Select month' => 'Selecionar mês',
    'Select time' => 'Selecionar hora',
    'Select year' => 'Selecionar ano',
    'Toggle meridiem' => 'Alternar período',
];
