<?php

declare(strict_types=1);

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Clear selection' => 'Сбросить выбор',
    'Close picker' => 'Закрыть выбор',
    'Date' => 'Дата',
    'Decrement hour' => 'Уменьшить час',
    'Decrement minute' => 'Уменьшить минуту',
    'Decrement second' => 'Уменьшить секунду',
    'Go to today' => 'Перейти на сегодня',
    'Increment hour' => 'Увеличить час',
    'Increment minute' => 'Увеличить минуту',
    'Increment second' => 'Увеличить секунду',
    'Next century' => 'Следующий век',
    'Next decade' => 'Следующее десятилетие',
    'Next month' => 'Следующий месяц',
    'Next year' => 'Следующий год',
    'Pick hour' => 'Выбрать час',
    'Pick minute' => 'Выбрать минуту',
    'Pick second' => 'Выбрать секунду',
    'Previous century' => 'Предыдущий век',
    'Previous decade' => 'Предыдущее десятилетие',
    'Previous month' => 'Предыдущий месяц',
    'Previous year' => 'Предыдущий год',
    'Select date' => 'Выбрать дату',
    'Select decade' => 'Выбрать десятилетие',
    'Select month' => 'Выбрать месяц',
    'Select time' => 'Выбрать время',
    'Select year' => 'Выбрать год',
    'Toggle meridiem' => 'Переключить период',
];
