<?php

declare(strict_types=1);

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Clear selection' => 'Auswahl löschen',
    'Close picker' => 'Picker schließen',
    'Date' => 'Datum',
    'Decrement hour' => 'Stunde verringern',
    'Decrement minute' => 'Minute verringern',
    'Decrement second' => 'Sekunde verringern',
    'Go to today' => 'Gehe zu heute',
    'Increment hour' => 'Stunde erhöhen',
    'Increment minute' => 'Minute erhöhen',
    'Increment second' => 'Sekunde erhöhen',
    'Next century' => 'Nächstes Jahrhundert',
    'Next decade' => 'Nächstes Jahrzehnt',
    'Next month' => 'Nächster Monat',
    'Next year' => 'Nächstes Jahr',
    'Pick hour' => 'Stunde auswählen',
    'Pick minute' => 'Minute auswählen',
    'Pick second' => 'Sekunde auswählen',
    'Previous century' => 'Vorheriges Jahrhundert',
    'Previous decade' => 'Vorheriges Jahrzehnt',
    'Previous month' => 'Vorheriger Monat',
    'Previous year' => 'Vorheriges Jahr',
    'Select date' => 'Datum auswählen',
    'Select decade' => 'Jahrzehnt auswählen',
    'Select month' => 'Monat auswählen',
    'Select time' => 'Zeit auswählen',
    'Select year' => 'Jahr auswählen',
    'Toggle meridiem' => 'Meridian umschalten',
];
