<?php

declare(strict_types=1);

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Clear selection' => 'Borrar selección',
    'Close picker' => 'Cerrar selector',
    'Date' => 'Fecha',
    'Decrement hour' => 'Reducir hora',
    'Decrement minute' => 'Reducir minuto',
    'Decrement second' => 'Reducir segundo',
    'Go to today' => 'Ir a hoy',
    'Increment hour' => 'Incrementar hora',
    'Increment minute' => 'Incrementar minuto',
    'Increment second' => 'Incrementar segundo',
    'Next century' => 'Próximo siglo',
    'Next decade' => 'Próxima década',
    'Next month' => 'Próximo mes',
    'Next year' => 'Próximo año',
    'Pick hour' => 'Seleccionar hora',
    'Pick minute' => 'Seleccionar minuto',
    'Pick second' => 'Seleccionar segundo',
    'Previous century' => 'Siglo anterior',
    'Previous decade' => 'Década anterior',
    'Previous month' => 'Mes anterior',
    'Previous year' => 'Año anterior',
    'Select date' => 'Seleccionar fecha',
    'Select decade' => 'Seleccionar década',
    'Select month' => 'Seleccionar mes',
    'Select time' => 'Seleccionar hora',
    'Select year' => 'Seleccionar año',
    'Toggle meridiem' => 'Alternar meridiano',
];
