<?php

declare(strict_types=1);

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Clear selection' => 'Effacer la sélection',
    'Close picker' => 'Fermer le sélecteur',
    'Date' => 'Date',
    'Decrement hour' => 'Décrémenter l\'heure',
    'Decrement minute' => 'Décrémenter la minute',
    'Decrement second' => 'Décrémenter la seconde',
    'Go to today' => 'Aller à aujourd\'hui',
    'Increment hour' => 'Incrémenter l\'heure',
    'Increment minute' => 'Incrémenter la minute',
    'Increment second' => 'Incrémenter la seconde',
    'Next century' => 'Siècle suivant',
    'Next decade' => 'Décennie suivante',
    'Next month' => 'Mois suivant',
    'Next year' => 'Année suivante',
    'Pick hour' => 'Sélectionner l\'heure',
    'Pick minute' => 'Sélectionner la minute',
    'Pick second' => 'Sélectionner la seconde',
    'Previous century' => 'Siècle précédent',
    'Previous decade' => 'Décennie précédente',
    'Previous month' => 'Mois précédent',
    'Previous year' => 'Année précédente',
    'Select date' => 'Sélectionner la date',
    'Select decade' => 'Sélectionner la décennie',
    'Select month' => 'Sélectionner le mois',
    'Select time' => 'Sélectionner l\'heure',
    'Select year' => 'Sélectionner l\'année',
    'Toggle meridiem' => 'Basculer le méridien',
];
