<?php

declare(strict_types=1);

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Clear selection' => '清除选择',
    'Close picker' => '关闭选择器',
    'Date' => '日期',
    'Decrement hour' => '减少小时',
    'Decrement minute' => '减少分钟',
    'Decrement second' => '减少秒数',
    'Go to today' => '转到今天',
    'Increment hour' => '增加小时',
    'Increment minute' => '增加分钟',
    'Increment second' => '增加秒数',
    'Next century' => '下个世纪',
    'Next decade' => '下个十年',
    'Next month' => '下个月',
    'Next year' => '明年',
    'Pick hour' => '选择小时',
    'Pick minute' => '选择分钟',
    'Pick second' => '选择秒数',
    'Previous century' => '上个世纪',
    'Previous decade' => '上个十年',
    'Previous month' => '上个月',
    'Previous year' => '去年',
    'Select date' => '选择日期',
    'Select decade' => '选择十年',
    'Select month' => '选择月份',
    'Select time' => '选择时间',
    'Select year' => '选择年份',
    'Toggle meridiem' => '切换时段',
];
